#!/bin/bash
#
# ZipDrop API - VPS Setup Script (Fully Automated)
# Run this on Ubuntu VPS (22.04+ recommended)
#
# ONE-LINER (after DNS is set up):
#   curl -sSL https://raw.githubusercontent.com/chrishacia/ZipDrop/main/server/setup-vps.sh | sudo bash
#

set -e  # Exit on any error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}"
echo "╔═══════════════════════════════════════════════════════════╗"
echo "║       ZipDrop API - Fully Automated VPS Setup             ║"
echo "╚═══════════════════════════════════════════════════════════╝"
echo -e "${NC}"

# Configuration
DOMAIN="zipdrop.woweggs.com"
REPO_URL="https://github.com/chrishacia/ZipDrop.git"
INSTALL_DIR="/opt/zipdrop"
NGINX_CONF="/etc/nginx/sites-available/zipdrop-api"

# Check if running as root
if [ "$EUID" -ne 0 ]; then
    echo -e "${RED}Please run as root: curl ... | sudo bash${NC}"
    exit 1
fi

# Generate secure random password (32 chars, alphanumeric + symbols)
DB_PASSWORD=$(openssl rand -base64 32 | tr -dc 'a-zA-Z0-9!@#$%' | head -c 32)
echo -e "${GREEN}Generated secure database password${NC}"

echo -e "${GREEN}[1/8]${NC} Updating system packages..."
apt-get update -qq
DEBIAN_FRONTEND=noninteractive apt-get upgrade -y -qq

echo -e "${GREEN}[2/8]${NC} Installing dependencies..."
DEBIAN_FRONTEND=noninteractive apt-get install -y -qq \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg \
    lsb-release \
    certbot \
    python3-certbot-nginx \
    git

# Handle NGINX - check if already installed
echo -e "${GREEN}[3/8]${NC} Configuring NGINX..."
if command -v nginx &> /dev/null; then
    echo -e "${YELLOW}NGINX already installed, using existing installation${NC}"
else
    echo "Installing NGINX..."
    DEBIAN_FRONTEND=noninteractive apt-get install -y -qq nginx
fi

# Ensure nginx is running
systemctl enable nginx 2>/dev/null || true
systemctl start nginx 2>/dev/null || true

echo -e "${GREEN}[4/8]${NC} Installing Docker..."
if ! command -v docker &> /dev/null; then
    curl -fsSL https://get.docker.com | sh
    systemctl enable docker
    systemctl start docker
    echo -e "${GREEN}Docker installed successfully${NC}"
else
    echo -e "${YELLOW}Docker already installed${NC}"
fi

# Install Docker Compose plugin if not present
if ! docker compose version &> /dev/null; then
    echo "Installing Docker Compose plugin..."
    DEBIAN_FRONTEND=noninteractive apt-get install -y -qq docker-compose-plugin
fi

echo -e "${GREEN}[5/8]${NC} Cloning repository..."
if [ -d "$INSTALL_DIR" ]; then
    echo -e "${YELLOW}Directory exists, pulling latest changes...${NC}"
    cd "$INSTALL_DIR"
    git pull origin main || true
else
    git clone "$REPO_URL" "$INSTALL_DIR"
fi

cd "$INSTALL_DIR/server"

echo -e "${GREEN}[6/8]${NC} Configuring environment..."
cat > .env << EOF
# ZipDrop API Configuration
# Generated by setup script on $(date)
# 
# DATABASE PASSWORD IS BELOW - Keep this file secure!
# Location: $INSTALL_DIR/server/.env

DB_PASSWORD=$DB_PASSWORD
NODE_ENV=production
PORT=3847
EOF

chmod 600 .env
echo -e "${GREEN}Environment file created with auto-generated password${NC}"
echo -e "${YELLOW}Password saved to: $INSTALL_DIR/server/.env${NC}"

echo -e "${GREEN}[7/8]${NC} Configuring NGINX reverse proxy..."

# Remove default site if it exists and is enabled
rm -f /etc/nginx/sites-enabled/default 2>/dev/null || true

cat > "$NGINX_CONF" << 'NGINX_EOF'
# ZipDrop API - NGINX Configuration
# Auto-generated by setup script

server {
    listen 80;
    listen [::]:80;
    server_name zipdrop.woweggs.com;

    location / {
        proxy_pass http://127.0.0.1:3847;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_cache_bypass $http_upgrade;
        proxy_read_timeout 90;
    }
}
NGINX_EOF

# Enable site (safe symlink)
ln -sf "$NGINX_CONF" /etc/nginx/sites-enabled/zipdrop-api

# Test nginx config
if nginx -t 2>/dev/null; then
    systemctl reload nginx
    echo -e "${GREEN}NGINX configured and reloaded${NC}"
else
    echo -e "${RED}NGINX config test failed, check manually${NC}"
fi

echo -e "${GREEN}[8/8]${NC} Starting Docker containers..."
cd "$INSTALL_DIR/server"
docker compose down 2>/dev/null || true
docker compose up -d --build

# Wait for containers to be healthy
echo "Waiting for services to start..."
sleep 15

# Check if API is responding
if curl -s http://localhost:3847/api/stats > /dev/null; then
    echo -e "${GREEN}✓ API is running on port 3847${NC}"
else
    echo -e "${YELLOW}API may still be starting up (check: docker compose logs -f)${NC}"
fi

# Attempt SSL setup with Let's Encrypt
echo ""
echo -e "${BLUE}[SSL Setup]${NC} Checking DNS..."
VPS_IP=$(curl -s ifconfig.me 2>/dev/null || echo "unknown")
DNS_IP=$(dig +short $DOMAIN 2>/dev/null | head -1)

if [ "$DNS_IP" = "$VPS_IP" ]; then
    echo -e "${GREEN}✓ DNS is properly configured ($DOMAIN -> $VPS_IP)${NC}"
    echo -e "${BLUE}[SSL Setup]${NC} Running Certbot..."
    
    if certbot --nginx -d $DOMAIN --non-interactive --agree-tos --register-unsafely-without-email --redirect; then
        echo -e "${GREEN}✓ SSL certificate installed successfully!${NC}"
        SSL_SUCCESS=true
    else
        echo -e "${YELLOW}Certbot failed - you may need to run it manually${NC}"
        SSL_SUCCESS=false
    fi
else
    echo -e "${YELLOW}DNS not yet pointing to this server${NC}"
    echo "  Domain: $DOMAIN"
    echo "  Expected IP: $VPS_IP"
    echo "  Current DNS: ${DNS_IP:-not resolved}"
    SSL_SUCCESS=false
fi

echo ""
echo -e "${BLUE}╔═══════════════════════════════════════════════════════════╗"
echo -e "║                    Setup Complete!                         ║"
echo -e "╚═══════════════════════════════════════════════════════════╝${NC}"
echo ""

if [ "$SSL_SUCCESS" = true ]; then
    echo -e "${GREEN}🎉 Everything is ready!${NC}"
    echo ""
    echo -e "API URL: ${GREEN}https://$DOMAIN${NC}"
    echo ""
    echo "Test it:"
    echo "  curl https://$DOMAIN/api/stats"
else
    echo -e "${YELLOW}Almost done! DNS setup required:${NC}"
    echo ""
    echo "1. Add DNS A record:"
    echo "   Host: zipdrop"
    echo "   Value: $VPS_IP"
    echo ""
    echo "2. Wait for DNS propagation (check: dig $DOMAIN)"
    echo ""
    echo "3. Run SSL setup:"
    echo "   sudo certbot --nginx -d $DOMAIN"
    echo ""
fi

echo -e "${GREEN}Useful commands:${NC}"
echo "  cd $INSTALL_DIR/server"
echo "  docker compose logs -f        # View logs"
echo "  docker compose restart        # Restart services"
echo "  cat .env                      # View DB password"
echo ""
echo -e "${GREEN}Database password saved to:${NC} $INSTALL_DIR/server/.env"
echo ""
